In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [2]:
train = pd.read_csv('train.csv')
train = train.drop(columns=["pred edge", "counterparty (naive)", "sm sentiment (naive)", "pnl"]).set_index("trade id")
test = pd.read_csv('test.csv').set_index("trade id").drop("pred edge", axis=1)

In [3]:
train = train.join(pd.get_dummies(train[["stock", "location", "dir", "counterparty"]]))
train = train.drop(columns=["stock", "location", "dir", "counterparty"])
train

,price,size,sm sentiment,realized edge,stock_A,stock_B,stock_C,stock_D,location_CSE,location_NASDAQ,location_NYSE,dir_B,dir_S,counterparty_HF,counterparty_MF,counterparty_R
trade id,,,,,,,,,,,,,,,,
0,98.507314,36.0,2.144241,-4.007551,0,1,0,0,1,0,0,0,1,1,0,0
1,14.935761,1094.0,-94.202156,-3.716749,0,0,1,0,1,0,0,0,1,1,0,0
2,99.818500,7.0,27.572105,11.867307,0,1,0,0,0,0,1,0,1,0,0,1
3,100.459287,59.0,-45.020574,-16.951884,0,1,0,0,1,0,0,1,0,1,0,0
4,15.209969,449.0,22.575639,-2.337918,0,0,1,0,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,98.290999,148.0,47.282761,-4.003388,0,1,0,0,0,0,1,0,1,0,0,1
199996,15.003929,327.0,-59.582576,0.522307,0,0,1,0,0,1,0,0,1,0,1,0
199997,2020.034449,2.0,96.035708,-25.712969,0,0,0,1,0,0,1,0,1,0,0,1
199998,99.224065,127.0,-90.732796,3.013510,0,1,0,0,0,0,1,0,1,0,0,1
199999,40.038205,392.0,32.275860,-3.759099,1,0,0,0,0,1,0,1,0,1,0,0

In [4]:
ss = StandardScaler()
x_train = train.drop("realized edge", axis=1)
x_train = ss.fit_transform(x_train)

y_train = train["realized edge"]

pd.DataFrame(x_train)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,-0.351655,-0.765465,0.040428,-0.502023,1.529820,-0.732316,-0.420504,1.998532,-0.818011,-0.814584,-0.99934,0.99934,2.001407,-0.905046,-0.733711
1,-0.471479,1.389028,-1.629198,-0.502023,-0.653672,1.365530,-0.420504,1.998532,-0.818011,-0.814584,-0.99934,0.99934,2.001407,-0.905046,-0.733711
2,-0.349775,-0.824520,0.481078,-0.502023,1.529820,-0.732316,-0.420504,-0.500367,-0.818011,1.227620,-0.99934,0.99934,-0.499648,-0.905046,1.362935
3,-0.348856,-0.718629,-0.776910,-0.502023,1.529820,-0.732316,-0.420504,1.998532,-0.818011,-0.814584,1.00066,-1.00066,2.001407,-0.905046,-0.733711
4,-0.471086,0.075561,0.394492,-0.502023,-0.653672,1.365530,-0.420504,-0.500367,1.222477,-0.814584,-0.99934,0.99934,-0.499648,1.104916,-0.733711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199995,-0.351965,-0.537390,0.822652,-0.502023,1.529820,-0.732316,-0.420504,-0.500367,-0.818011,1.227620,-0.99934,0.99934,-0.499648,-0.905046,1.362935
199996,-0.471381,-0.172878,-1.029261,-0.502023,-0.653672,1.365530,-0.420504,-0.500367,1.222477,-0.814584,-0.99934,0.99934,-0.499648,1.104916,-0.733711
199997,2.403418,-0.834702,1.667512,-0.502023,-0.653672,-0.732316,2.378099,-0.500367,-0.818011,1.227620,-0.99934,0.99934,-0.499648,-0.905046,1.362935
199998,-0.350627,-0.580154,-1.569076,-0.502023,1.529820,-0.732316,-0.420504,-0.500367,-0.818011,1.227620,-0.99934,0.99934,-0.499648,-0.905046,1.362935
199999,-0.435487,-0.040513,0.562591,1.991942,-0.653672,-0.732316,-0.420504,-0.500367,1.222477,-0.814584,1.00066,-1.00066,2.001407,-0.905046,-0.733711

In [5]:
test = test.join(pd.get_dummies(test[["stock", "location", "dir", "counterparty (naive)"]]))
test = test.drop(columns=["stock", "location", "dir", "counterparty (naive)"])
test

x_test = ss.transform(test)
pd.DataFrame(x_test)
test

,price,size,sm sentiment (naive),stock_A,stock_B,stock_C,stock_D,location_CSE,location_NASDAQ,location_NYSE,dir_B,dir_S,counterparty (naive)_HF,counterparty (naive)_MF,counterparty (naive)_R
trade id,,,,,,,,,,,,,,,
0,14.727382,1346.0,9.119066,0,0,1,0,0,0,1,1,0,0,1,0
1,15.016002,882.0,-48.652384,0,0,1,0,1,0,0,0,1,0,1,0
2,15.169420,423.0,3.536848,0,0,1,0,0,0,1,1,0,0,1,0
3,2026.572586,8.0,48.257293,0,0,0,1,1,0,0,1,0,0,1,0
4,15.027723,523.0,-66.590908,0,0,1,0,0,0,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1995.388892,1.0,-85.018229,0,0,0,1,0,0,1,1,0,1,0,0
99996,99.420082,51.0,43.210479,0,1,0,0,0,1,0,0,1,0,1,0
99997,40.410974,270.0,29.156088,1,0,0,0,0,1,0,0,1,1,0,0
99998,15.090556,787.0,-91.163595,0,0,1,0,0,0,1,1,0,0,1,0
99999,40.171264,485.0,89.445168,1,0,0,0,0,0,1,0,1,0,0,1

In [6]:
train.drop("realized edge", axis=1).head()

,price,size,sm sentiment,stock_A,stock_B,stock_C,stock_D,location_CSE,location_NASDAQ,location_NYSE,dir_B,dir_S,counterparty_HF,counterparty_MF,counterparty_R
trade id,,,,,,,,,,,,,,,
0,98.507314,36.0,2.144241,0,1,0,0,1,0,0,0,1,1,0,0
1,14.935761,1094.0,-94.202156,0,0,1,0,1,0,0,0,1,1,0,0
2,99.818500,7.0,27.572105,0,1,0,0,0,0,1,0,1,0,0,1
3,100.459287,59.0,-45.020574,0,1,0,0,1,0,0,1,0,1,0,0
4,15.209969,449.0,22.575639,0,0,1,0,0,1,0,0,1,0,1,0

# Linear Regression

In [7]:
from sklearn.linear_model import LinearRegression

In [8]:
lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = pd.DataFrame(lr.predict(x_test))

In [9]:
y_pred.index.name = "trade id"
y_pred.columns = ["realized edge"]

In [10]:
y_pred

          realized edge
trade id
0              2.307578
1             -1.471719
2              4.608359
3             -0.313516
4              4.299765
...                 ...
99995         -1.473672
99996          0.604453
99997         -4.317422
99998          3.618125
99999          4.012656

[100000 rows x 1 columns]

In [11]:
y_pred.to_csv("pred.csv")

# LGBM

In [12]:
import lightgbm as lgb

In [13]:
x_train.shape

(200000, 15)

In [34]:
lgb_train = lgb.Dataset(x_train[:175000], y_train[:175000])
lgb_eval = lgb.Dataset(x_train[175000:], y_train[175000:], reference=lgb_train)

# specify your configurations as a dict
params = {
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'metric': {"rmse"},
    'num_leaves': 1000,
    'learning_rate': .01,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0
}

gbm = lgb.train(params,
                lgb_train,
                num_boost_round=5000,
                valid_sets=lgb_eval,
                callbacks=[lgb.early_stopping(stopping_rounds=100, verbose=True)])

[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.025601 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[338]	valid_0's rmse: 6.23089

In [31]:
lgb_train = lgb.Dataset(x_train, y_train)
lgb_eval = lgb.Dataset(x_train, y_train, reference=lgb_train)

# specify your configurations as a dict
params = {
    'boosting_type': 'gbdt',
    'objective': 'regression',
    'metric': {"rmse"},
    'num_leaves': 1000,
    'learning_rate': 1,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0
}

gbm = lgb.train(params,
                lgb_train,
                num_boost_round=500,
                valid_sets=lgb_eval,
                callbacks=[lgb.early_stopping(stopping_rounds=50, verbose=True)]
                )

[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.010183 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
Training until validation scores don't improve for 50 rounds
Did not meet early stopping. Best iteration is:
[500]	valid_0's rmse: 0.813867

In [35]:
pred_lgb = pd.DataFrame(gbm.predict(x_test))
pred_lgb.index.name = "trade id"
pred_lgb.columns = ["realized edge"]
pred_lgb

          realized edge
trade id
0              3.118430
1             -0.409482
2              3.706775
3            -14.071193
4              4.632017
...                 ...
99995         -0.080713
99996          1.403069
99997         -3.707263
99998          2.974835
99999        -21.182789

[100000 rows x 1 columns]

In [36]:
pred_lgb.to_csv("pred_lgb.csv")